### ISSUE TITLE
Error: Cannot find module './RootComponents'

### ISSUE THREAD

**Issue by poorpaddy** [nozzle/react-static#170]
After updating to 4.2.0 and running dev server I get `Error: Cannot find module './RootComponents'`. It appears the file is there but not being compiled and copied over to lib in node_modules.

**Comment by EmilTholin** [comment]
Can confirm. I just tried `react-static@4.2.0` with the `react-static create` command and got the following error:

```bash
Error: Cannot find module './RootComponents'
```

It looks like only a part of the `lib` folder got published, and the entire `src` folder is included as well. That's odd.

<img width="201" alt="part_of_lib_folder" src="https://user-images.githubusercontent.com/11573167/32794963-98e5c684-c96a-11e7-9dd3-cb995ffebba0.png">

**Comment by poorpaddy** [comment]
I've tested the src build locally and it does copy it over correctly. Is it possible a build didn't occur before releasing to npm?

**Comment by EmilTholin** [comment]
Yep, it works flawlessly when compiling it yourself from a fork. I'm not sure what has happened. It might be a conflict between the `.npmignore` and `.gitignore` files (?), or maybe the build didn't complete before publishing.

**Comment by poorpaddy** [comment]
I'm guessing the latter. Only `.gitignore` has changed with the last release and while lib is excluded nothing that would single out the single file.

**Comment by poorpaddy** [comment]
Temp solution until next release is to navigate to `/node_modules/react-static` and `npm run build`.

**Comment by tannerlinsley** [comment]
Fixed in the latest release. Something went wrong with the release process and it uploaded a partial file.

**Comment by tannerlinsley** [comment]
Close on confirmation :)

**Comment by poorpaddy** [comment]
4.2.1 resolves this issue.
