### ISSUE TITLE
[v6] ESM imports from node_modules are not being processed correctly

### ISSUE THREAD

**Issue by loganfromlogan** [nozzle/react-static#791]
**Describe the bug**
Just upgraded from beta 22 to beta 24. Ran `react-static start`, load the site and get the error
```javascript
Uncaught TypeError: (0 , _reactEmotion2.default) is not a function
```

**Expected behavior**
That emotion's default export will work within ReactStatic

**Screenshots**
![image](https://user-images.githubusercontent.com/5152553/46482585-1dedd780-c7b3-11e8-9ec6-44a6430e4f00.png)

**Desktop (please complete the following information):**
 - OS: macOS (Mojave)
 - Browser: Chrome
 - Version: 69

**Comment by tannerlinsley** [comment]
This could have been caused by #775. @digitalkaoz, looks like we need to refine that concept a bit more?

**Comment by digitalkaoz** [comment]
@tannerlinsley mh the babel stuff is probably identical to CRA, so what might be wrong here?

**Comment by digitalkaoz** [comment]
@loganfromlogan can you show me a piece of the source code how you integrate emotion?

**Comment by tannerlinsley** [comment]
There is an emotion example in the v6 branch you can look at
