### ISSUE TITLE
TypeError: (0 , _reactStatic.cleanPath) is not a function

### ISSUE THREAD

**Issue by t2** [nozzle/react-static#428]
After upgrading to 5.3.4 I get this error when running `yarn start` or `yarn build`:

```
=> Exporting HTML...
TypeError: (0 , _reactStatic.cleanPath) is not a function
    at render (/Users/Trent/Projects/airship/airship/teamairship.com/dist/static.3a5b76ee.js:921:42)
    at Route.render (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/react-router/Route.js:124:13)
    at resolve (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:2149:18)
    at ReactDOMServerRenderer.render (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:2260:22)
    at ReactDOMServerRenderer.read (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToString (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at renderToStringAndExtract (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/gitdocs/node_modules/react-static/lib/static.js:453:68)
    at _callee2$ (/Users/Trent/Projects/airship/airship/teamairship.com/static.config.js:46:18)
    at tryCatch (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/regenerator-runtime/runtime.js:62:40)
    at Generator.invoke [as _invoke] (/Users/Trent/Projects/airship/airship/teamairship.com/node_modules/regenerator-runtime/runtime.js:296:22)
```

**Comment by tannerlinsley** [comment]
Fixed in beta
