### ISSUE TITLE
Error: Cannot find module '../lib/utils/binHelper'

### ISSUE THREAD

**Issue by gastonmorixe** [nozzle/react-static#713]
`../lib/utils/binHelper` shouldn't be `../src/utils/binHelper` ?

**Comment by elassol** [comment]
Did you solve the issue?

**Comment by gastonmorixe** [comment]
@elassol nop. abandoned the idea of using react-static sadly until it works with babel 7 out-of-the-box.

**Comment by briaguya** [comment]
I encountered this issue as well:
I first tried: `yarn add react-static@next` and ran into #701 
Then I tried adding master using `yarn add https://github.com/nozzle/react-static`
I then cd'd into the node_modules/react-static dir and ran `yarn build` so the lib folder would show up and it started working.

**Comment by benadamstyles** [comment]
The `src` folder doesn't exist, if you install using `npm` rather than `yarn`!

**Comment by nozzle** [comment]
Info: `master` branch now points to 5.x.x and the `v6` branch to 6.0.0-beta.

**Comment by hmedney** [comment]
I've upgraded a 5.x project using both `yarn add react-static@latest` and `yarn add https://github.com/nozzle/react-static` - been hitting:

```bash
Error: Cannot find module '../lib/utils/binHelper'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/mnt/d/dev/project/ReactStatic/node_modules/react-static/bin/react-static-start:4:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by vision669** [comment]
same issue please fix

**Comment by robbyemmert** [comment]
What versions of NPM are react-static known to work with? Also, any idea when this was changed? What is the latest known working version of react-static?

**Comment by robbyemmert** [comment]
I found the issue. They're tagging beta builds with the 'latest' tag, which makes npm install the latest beta version by default (which happens to be broken at the moment).

Workaround to install the latest stable version: 
npm uninstall -g react-static
npm install -g react-static@v5.9.5

@tannerlinsley A quick npm tagging fix can likely avoid confusion like this in the future. NPM recommends tagging only the latest version releases with the 'latest' tag, and tagging beta releases with a 'beta' tag. Read the TLDR here: https://docs.npmjs.com/getting-started/using-tags. The latest tag should technically point to v5.9.5, and the 'beta' tag should point to the latest version.

I filed a separate issue to fix the tagging. See #740

**Comment by tannerlinsley** [comment]
Responded to the other issue. This was absolutely a mixup. Latest should be
pointing at 5.x and @next should point to the beta. I'll fix this asap

**Comment by robbyemmert** [comment]
FYI I'm currently still getting this issue when I install 5.9.5 manually via the github release.

**Comment by luchoster** [comment]
After seeing this issue, I changed my package.json to be `^5.9.5` , deleted my yarn.lock and node_modules/ and re-installed. That worked fine. 
The problem is when starting a new project, as stated before.

**Comment by ashrewdmint** [comment]
This seems to be happening for me with `react-static` at `^6.0.10`. I'm currently investigating it.

```
$ yarn start
yarn run v1.9.4
warning ../package.json: No license field
$ react-static start
internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module '../lib/utils/binHelper'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at start (/Users/andrew/Vidiq/marketing2/node_modules/react-static/bin/react-static:115:3)
    at init (/Users/andrew/Vidiq/marketing2/node_modules/react-static/bin/react-static:32:12)
    at Object.<anonymous> (/Users/andrew/Vidiq/marketing2/node_modules/react-static/bin/react-static:5:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```

**Comment by farskid** [comment]
@ashrewdmint Happened to right now when upgraded from v6.0.8 to v6.0.10.

**Comment by ashrewdmint** [comment]
It seems like you have to make sure the `rimraf` package is installed, and also that you `cd` into the `react-static` package in `node_modules` and run `yarn build`. Then it works.

**Comment by tannerlinsley** [comment]
This should not be necessary and it's definitely a bug. I'll look into it
asap

**Comment by tannerlinsley** [comment]
Upgrade to 6.0.11 and try again?

**Comment by farskid** [comment]
@tannerlinsley Fixed by upgrading to v6.0.11 👍

**Comment by andrew8er** [comment]
I have this exact issue in 6.3.7. Running `yarn build` in `node_modules/react-static` solves it temporarily.

**Comment by tannerlinsley** [comment]
I'll look into this asap.

**Comment by tannerlinsley** [comment]
Just published a new version (6.3.8) that should fix this issue. Still working out a bug where our lerna setup will publish partially built files and bust.

**Comment by Burnett2k** [comment]
Just dropping by to say I'm getting this issue as well. It is not happening on my local machine, but only on a docker container when I try and deploy to production.  Upgrading to 6.3.8 should fix it?

**Comment by tannerlinsley** [comment]
Yep!

Tanner Linsley

**Comment by ajkasliwal** [comment]
@tannerlinsley I have just updated to 6.3.8 and still getting this issue.


F:\Application>npm install -g react-static
npm WARN deprecated core-js@1.2.7: core-js@<2.6.5 is no longer maintained. Pleas
e, upgrade to core-js@3 or at least to actual version of core-js@2.
C:\Users\ADMIN\AppData\Roaming\npm\react-static -> C:\Users\ADMIN\AppData\Roamin
g\npm\node_modules\react-static\bin\react-static
npm WARN react-static@6.3.8 requires a peer of react-hot-loader@^4.3.12 but none
 is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\rea
ct-static\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"
})

+ react-static@6.3.8
updated 1 package in 131.34s

F:\Application>react-static create
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '../lib/utils/binHelper'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at create (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\react-static\bin\
react-static:94:3)
    at init (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\react-static\bin\re
act-static:29:12)
    at Object.<anonymous> (C:\Users\ADMIN\AppData\Roaming\npm\node_modules\react
-static\bin\react-static:5:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)

**Comment by Burnett2k** [comment]
Hmm, that didn't seem to work. Should I stay on an earlier version of 6.x.x that is more stable?

**Comment by tannerlinsley** [comment]
I would try it in a fresh docker setup. If it works in a CI it shouldn't have problems in docker. Maybe it's caching the old version?

Tanner Linsley

**Comment by Burnett2k** [comment]
I've tried a lot of things and it is still broken in Docker setup, but works fine on my local. Judging from activity on this thread, I don't think this is resolved. Is there a possibility I need to move to a newer version of one of the react-static jss plugins or the eslint config for react-tools?

DO you think this warning could be an important clue as to why it isn't working in Docker? `info fsevents@1.2.7: The platform "linux" is incompatible with this module.`

**Comment by tannerlinsley** [comment]
You could start by checking if the `node_modules/react-static/lib` directory exists after running `yarn` in the container. If it doesn't, then I would like to know the version that is in the `node_modules/react-static/package.json` file.

If the `lib` directory is there, then check for the `lib/utils/binHelper.js` file. If the `lib` directory exists with some files, but not this one, then that means there was a partial publish to NPM. 

If `lib/utils/binHelper.js` exists, and it still insists that it cannot find it, then:
- If you are running `react-static build`
  - Is `react-static` installed globally in your containers global node_modules? Locate it and try these steps again.
- If you are running an npm script like `npm run build / yarn build`
  - It should be using the local node_modules copy of `react-static`. If this is true, then we'll need to debug further.

**Comment by lsroman** [comment]
https://npm.runkit.com/react-static and https://bundlephobia.com/result?p=react-static say that the package is broken

**Comment by tannerlinsley** [comment]
Looks like there was a partial build that got published: https://unpkg.com/react-static@6.3.8/lib/

I'll go check the logs and see what happened. Lerna has been acting up a bit in the v6 branch for some reason.

**Comment by Burnett2k** [comment]
Any news on this? Do you think the 6.3.8 will get reuploaded?

**Comment by tannerlinsley** [comment]
I've confirmed that there was an npm packing issue in v6. I've issued a patch version that hopefully takes care of it. Yes v7 is out now, feel free to upgrade when convenient.
